services:
  - name: kanji-panda-be
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kanji_panda
          property: connectionString

buildCommand:
  - npm install
  - npm run build

startCommand: npm start
